[package]
name = "benchamark"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "client"
path = "src/bin/client.rs"

[[bin]]
name = "server"
path = "src/bin/server.rs"


[dependencies]

[build-dependencies]
tonic-build = {path = "../tonic-build", features = ["prost"]}
